### ISSUE TITLE
Autocomplete for Morganey

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/morganey-intellij-plugin#3]
The plugin should also add Auto Completion capabilities for the Morganey language

**Comment by keddelzz** [comment]
The [ReplAutocompletion of Morganey](https://github.com/morganey-lang/Morganey/blob/49e37dc9505721634058bf6adbff14338daca461/src/main/scala/me/rexim/morganey/ReplAutocompletion.scala) might help you with this feature.

**Comment by 06needhamt** [comment]
This will be very helpful Thanks
