### ISSUE TITLE
Show Raw terms on key-press

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/morganey-intellij-plugin#6]
It would be very cool, if there's a configurable key, which shows the raw term (like the `:raw` command) similar to "Type Info" in IntelliJs Scala plugin.

For example:
If I select a term like `(5 6)` in the editor and press a key, it should show `(\f.x.f (f (f (f (f x))))) (\f.x.f (f (f (f (f (f x))))))`.

**Comment by keddelzz** [comment]
@morganey-lang/intellij-idea-plugin-team could anyone of you please add the `proposal` label? I can't add it myself. :)

**Comment by keddelzz** [comment]
Thank you @06needhamt :+1:

**Comment by 06needhamt** [comment]
@keddelzz Feature is now live https://github.com/morganey-lang/morganey-intellij-plugin/commit/323df1fadc39d8218c357bff9b8f3e1ccc805eb1 let me know what you think the key is CTRL+ALT+R

**Comment by keddelzz** [comment]
I'm experiencing a weird behavior with the popup. Everytime I press CTRL+ALT+R the raw term gets added to the text, which is visible in the popup.

![morganey-intellij-plugin-popup-bug ong](https://cloud.githubusercontent.com/assets/3746739/19009165/4a627188-8771-11e6-905e-7974b999eb7f.png)

**Comment by keddelzz** [comment]
Also, if I press CTRL+ALT+R while I have selected an invalid term an exception is thrown in the console. You might want to handle the error.  `ParseResult[T]` has a `isSuccess` method to test if the parsing was successful. This should be preferred instead of using the `get()` method [here](https://github.com/morganey-lang/morganey-intellij-plugin/blob/323df1fadc39d8218c357bff9b8f3e1ccc805eb1/src/com/morganey/actions/ViewRawTermAction.kt#L38).

**Comment by keddelzz** [comment]
Also I have to confess, that I've imagined a different kind of popup. I imagined a notification like the `Type-Info` in the IntelliJ's Scala plugin.

![intellij-scala-plugin-popup](https://cloud.githubusercontent.com/assets/3746739/19009309/bb3794c8-8772-11e6-8717-7ff773ff5a7d.png)

## 

But I'm fine with either popup kind.

**Comment by keddelzz** [comment]
Other than that, nice work :+1:

**Comment by 06needhamt** [comment]
@keddelzz All These Issues Should Be Fixed Now Let Me Know If Anything Else Should Be Done

**Comment by keddelzz** [comment]
Wow, I love the new popup. In my opinion it's much more beautiful now! :+1: 

![morganey-intellij-plugin-raw-term](https://cloud.githubusercontent.com/assets/3746739/19014421/b3096bda-87ec-11e6-9de0-5a3c6252852b.png)

**Comment by keddelzz** [comment]
There's still one problem: You parse a term four times for showing the raw term.
- Terms are parsed two times for each call of the function [`ParseTermScala.parse`](https://github.com/morganey-lang/morganey-intellij-plugin/blob/de089dbad29e96f0a6da7b5f3bc71c4682971ba1/src/com/morganey/ParseTermScala.scala#L36)
- The function `ParseTermScala.parse` is called two times [here](https://github.com/morganey-lang/morganey-intellij-plugin/blob/de089dbad29e96f0a6da7b5f3bc71c4682971ba1/src/com/morganey/actions/ViewRawTermAction.kt#L27)

If you want I can fix this in a PR. :)

**Comment by keddelzz** [comment]
I've submitted a PR, see #11

**Comment by 06needhamt** [comment]
Merged PR #11 Thanks a lot

**Comment by 06needhamt** [comment]
Close #6 For now reopen if necessary

**Comment by keddelzz** [comment]
Thank you for implementing this feature, this is really cool :+1:

**Comment by 06needhamt** [comment]
Thank you for helping me out still getting used to scala and the morganey
code base
