### ISSUE TITLE
Fix invalid file extension

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/morganey-intellij-plugin#7]
Change file extension `morg` defined
- [here](https://github.com/morganey-lang/morganey-intellij-plugin/blob/a23553cd0e2f12b28d60129fd2f8a733ab1fa197/src/com/morganey/filetype/MorganeyFileType.kt#L54)
- [and here](https://github.com/morganey-lang/morganey-intellij-plugin/blob/a23553cd0e2f12b28d60129fd2f8a733ab1fa197/src/com/morganey/filetype/MorganeyFileTypes.kt#L39)

to `mgn`.

**Comment by rexim** [comment]
Agreed. `.mgn` is the official Morganey extension: https://github.com/morganey-lang/Morganey/issues/147#issuecomment-244610647

**Comment by 06needhamt** [comment]
Thanks for the report

Closed #7 https://github.com/morganey-lang/morganey-intellij-plugin/commit/50b995daf63d870de040862030f164d97d6a981c
