### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/morganey-intellij-plugin#8]
I think the description [here](https://github.com/morganey-lang/morganey-intellij-plugin/blob/a23553cd0e2f12b28d60129fd2f8a733ab1fa197/src/com/morganey/filetype/MorganeyFileType.kt#L62) comes from a copy and pasting from [your Neuroph-Intellij-Plugin](https://github.com/06needhamt/Neuroph-Intellij-Plugin). It has to be adapted to Morganey.

**Comment by 06needhamt** [comment]
Thanks for the Report 

Closed #8 https://github.com/morganey-lang/morganey-intellij-plugin/commit/6acf32716a42e4d0551372fa0382a57229bbb946
